apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
spec:
  selector:
    matchLabels:
      app: voting-app-deploy
  template:
    metadata:
      labels:
        app: voting-app-deploy
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  type: NodePort
  selector:
    app: voting-app-deploy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
