apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      name: myapp
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        name: myapp
        env: production
    spec:
      containers:
      - name: nginx-2
        image: nginx
     
